[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter = "31nkast5V8Xx7uyZDQSqfQPqNzHhFXxP9LAXm88MTJNM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kevinweng/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
